### ISSUE TITLE
Can't copy files from VM to host

### ISSUE THREAD

**Issue by AndromedaMelody** [M2Team/NanaBox#1]
There is no feedback and can't find the file in Explorer after clicking 'Paste'.

**Comment by MouriNaruto** [comment]
The issue is resolved. So, I closed the issue.

https://github.com/M2Team/NanaBox/commit/83c199cb204da8984283a7a03b94ae041a4215c9

Kenji Mouri

**Comment by MouriNaruto** [comment]
Because the previous solution is not working. I have updated a new solution.

https://github.com/M2Team/NanaBox/commit/1261c45205d7a179d25799c049f4bfe2e011f8e9

Kenji Mouri
