### ISSUE TITLE
Access is denied if VHDX is located in %SystemDrive%\\Users\\**\\*

### ISSUE THREAD

**Issue by AndromedaMelody** [M2Team/NanaBox#2]
![Screenshot 2022-07-31 143151](https://user-images.githubusercontent.com/57533055/182013393-c9c0dd97-4f2f-460d-b77b-1041d0f11254.png)

**Comment by MouriNaruto** [comment]
![image](https://user-images.githubusercontent.com/10867563/185767435-f272e676-41db-4a04-9c08-1bed19b7f52d.png)

This issue has been fixed, proved by the screenshot.

Kenji Mouri
