### ISSUE TITLE
RDP auto-resizing issue on Hi-DPI + maximized window

### ISSUE THREAD

**Issue by dongle-the-gadget** [M2Team/NanaBox#24]
When the following conditions are met:
- Enhanced Session is disabled
- The display is high DPI (that is, scaling is more than 100%, haven't tested custom scaling)
- The VM changes resolution

The RDP control would improperly resize, creating black regions where input is accepted, but nothing is displayed.

<img width="1128" alt="Screenshot of bug" src="https://github.com/user-attachments/assets/3fdb0723-2f6d-42a6-acb1-b7722897e2f6">

**Comment by MouriNaruto** [comment]
This issue should be fixed since [this commit](https://github.com/M2Team/NanaBox/commit/27b3ad12f1f4d88355cc050a1c9ff6a354dd6f2f).

Kenji Mouri
