### ISSUE TITLE
Feature request: recently launched VMs history

### ISSUE THREAD

**Issue by Drakknar** [M2Team/NanaBox#25]
It would be useful to add a section to NanaBox's launch screen which lists - and allows to start - the most recently launched VMs. It should be possible to clear such list through a dedicated option. 

As an alternative, the "Launch virtual machine" button could be turned into a Combo Button (or Split button as Microsoft calls it in the WinUI documentation) that combines the regular "Launch virtual machine" functionality with flyout listing the most recently launched VMs and a command on the very bottom to delete all the elements in the list.

**Comment by MouriNaruto** [comment]
> NanaBox chooses Host Compute System API instead of Hyper-V WMI Providers because the author (Kenji Mouri) wants to have portable virtual machine configurations and feels disgusting for registering virtual machine configurations into system.

Reference: https://github.com/M2Team/NanaBox/blob/main/ReadMe.md

Kenji Mouri
