### ISSUE TITLE
从Microsoft Store安装nanabox以及用自行组装的安装包安装nanabox，启动时会出现如下图的错误

### ISSUE THREAD

**Issue by peashooter2** [M2Team/NanaBox#27]
![屏幕截图 2024-12-01 211432](https://github.com/user-attachments/assets/f0ddca05-211b-46c4-a985-999578deb408)
Microsoft Store的NanaBox版本：1.3.874.0
自行组装的安装包的NanaBox版本：1.5.974.0
自行组装的NanaBox安装包下载链接：https://www.123865.com/s/8otmjv-PEPVv

**Comment by MouriNaruto** [comment]
你目前提供的信息太过有限，倒是你要是使用 VS 调试一下 NanaBox 也许能找到问题吧

这个错误我没有遇到过，而且 NanaBox 在 GitHub Releases 提供便携式版本

毛利
