### ISSUE TITLE
Expose Nested Virtualization option in Settings (VM does not start on AMD Windows 10 host and ARM host)

### ISSUE THREAD

**Issue by driver1998** [M2Team/NanaBox#3]
Currently NanaBox hardcodes nested virtualization support to be enabled.
Nested Virtualization support in Hyper-V for AMD processors is not available until Server 2022 (Iron), and still not available yet on ARM. Which means NanaBox VMs won't start at all on AMD machines with Windows 10, or ARM machines.

**Comment by MouriNaruto** [comment]
Thank you for noticing that.

I will provide this feature starting with the next preview version or NanaBox 1.0 Preview 2.

Kenji Mouri

**Comment by MouriNaruto** [comment]
The issue is resolved. So, I closed the issue.

https://github.com/M2Team/NanaBox/commit/7353146bfcbd94d80b016285ed3b272c49712711

Kenji Mouri
