### ISSUE TITLE
Windows VM sometimes stuck on blackscreen

### ISSUE THREAD

**Issue by xLSX285** [M2Team/NanaBox#5]
First of all, congrats on the first stable release of Nanabox. I've been using it since preview 1.

**EDIT://** I noticed on the stable release, when Windows is the chosen OS and either you or Windows performs a restart, it will sometimes stay stuck on a blackscreen. To fix this, you can either force-restart the VM or switch on and off enhanced session to get rid of the blackscreen.

- I'm able to reproduce this **sometimes** on [1.0.471.0 (Stable)](https://github.com/M2Team/NanaBox/releases/tag/1.0.471.0). This doesn't occur on [Preview 2](https://github.com/M2Team/NanaBox/releases/tag/1.0.247.0) or older releases of Nanabox.

**Comment by MouriNaruto** [comment]
Thanks for your support.

I will try my best to reproduce that.

I think I will refactor the current implementation first. Maybe it can resolve your issue.

Kenji Mouri

**Comment by xLSX285** [comment]
I just wanted to provide an update regarding this issue.

_I'm no longer able to reproduce this in any of the new versions of Nanabox._ 

Assuming this issue has been adressed, or it was actually something bad on my end.
