### ISSUE TITLE
Short question: Does your in app RDP client overcomes RDP max 30 fps limitation?

### ISSUE THREAD

**Issue by etapic** [M2Team/NanaBox#6]
Hello, 
Sadly at this moment I didn't managed to launch NanaBox successfully, so I can't test it myself  (working on that :) )

Does your in app RDP client overcomes RDP max 30 fps limitation? Lets say on windows 10 vm, directx 11 application.

**Comment by MouriNaruto** [comment]
I use Microsoft RDP ActiveX control implementation as the RDP client. So, I think it should be OK if you can solve the issue for Microsoft Remote Desktop Client.

Kenji Mouri
