### ISSUE TITLE
The Save As window renames folder interface freezes

### ISSUE THREAD

**Issue by Jarung** [M2Team/NanaBox#7]
创建虚拟机时在另存为窗口重命名文件夹界面卡住

Nanabox version (Nanabox版本)
1.1.600.0

Windows build number (Windows 内部版本号)
10.0.19044.3693

Steps to reproduce 重现步骤
1.Open Nanabox and click Create VM 
(打开Nanabox，点击创建虚拟机)
2.In the Save As window, right-click to create a new folder and rename the folder.
(弹出的另存为窗口中，右键新建文件夹，然后重命名刚刚新建的文件夹)

Expected Behavior 预期行为
Able to rename normally
(能够正常重命名)

Actual Behavior 实际行为
The rename operation cannot be completed, and the window freezes.
(重命名操作无法完成，窗口无法进行任何操作)

**Comment by MouriNaruto** [comment]
This issue should be solved by https://github.com/M2Team/NanaBox/commit/41a5fec62dfc7649f027615796b4ce966b86aeca.

Kenji Mouri
