### ISSUE TITLE
NanaBox crashes when closed

### ISSUE THREAD

**Issue by Jarung** [M2Team/NanaBox#8]
NanaBox version (NanaBox版本)
1.1.600.0

Windows build number (Windows 内部版本号)
10.0.19044.3693

Steps to reproduce 重现步骤
1.Open Nanabox;
(打开Nanabox)
2.Click the close button.
(点击右上角关闭按钮)

Expected Behavior 预期行为
Shut off normally
(正常关闭)

Actual Behavior 实际行为
NanaBox crashes and closes by itself
(Nanabox崩溃，然后关闭)

dump文件已通过qq传送
![20231123134340](https://github.com/M2Team/NanaBox/assets/10348075/dab41f27-72dd-4e18-b645-dbcf36ce7b4f)

**Comment by MouriNaruto** [comment]
Maybe the issue should be solved in the 1.2.x.

I close the issue first. Please feel free to open a new issue if you encounter the same issue like that.

Kenji Mouri
